name: Test ARC Autopilot
on: 
  workflow_dispatch:

jobs:
  demo:
    runs-on: arcautopilot
    container: debian:stable-slim
    steps:
      - run: echo "ARC Autopilot corriendo en GKE Autopilot con token"

