name: Test ARC Autopilot
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: arcautopilot
    container: ghcr.io/chainguard-images/busybox:latest
    steps:
      - name: Hello
        run: |
          echo "âœ… ARC Autopilot en GKE listo"
          uname -a
          echo "Repo: $GITHUB_REPOSITORY"
