name: Test ARC Autopilot
on: { workflow_dispatch: {} }

jobs:
  demo:
    runs-on: arcautopilot
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
    steps:
      - name: Hello from GKE Autopilot
        run: |
          echo "âœ… ARC Autopilot ejecutando en GKE"
          echo "Runner: $RUNNER_NAME"
          uname -a
