name: Test ARC Autopilot
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: arcautopilot
    steps:
      - name: Chequear entorno
        run: |
          echo "ARC Autopilot corriendo en GKE Autopilot"
          uname -a
          df -h
          echo "GitHub repo: $GITHUB_REPOSITORY"

